import '../styles/app.scss';
import localFont from 'next/font/local';
import { Red_Hat_Display } from 'next/font/google';
import Header from './Header';

const fontMelodrama = localFont({ src: '../assets/fonts/Melodrama-Variable.ttf', display: 'swap', variable: '--font-melodrama' });
const fontRed_Hat_Display = Red_Hat_Display({ subsets: ['latin'], display: 'swap', weight: 'variable' });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${fontMelodrama.variable} ${fontRed_Hat_Display.variable} ${fontRed_Hat_Display.className}`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
