import "../styles/app.scss";
import localFont from "next/font/local";
import { Red_Hat_Display } from "next/font/google";
import Header from "./Header";

const fontMelodrama = localFont({ src: "../assets/fonts/Melodrama-Variable.ttf", display: "swap", variable: "--font-melodrama" });
const fontRHD = Red_Hat_Display({ subsets: ["latin"], display: "swap", weight: "variable", variable: "--font-rhd" });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${fontMelodrama.variable} ${fontRHD.variable} ${fontRHD.className}`} data-scroll-container>
				<Header />
				{children}
			</body>
		</html>
	);
}
